version: '3.1'

services:
  db:
    image: postgres:12.6-alpine
    restart: always
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379"

  app:
    build: .
    restart: always
    command: bash -c "/app/entrypoint.sh"
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST}
      - DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_HOST_USER}
      - DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD}
      - DJANGO_SOCIAL_AUTH_GITHUB_KEY=${DJANGO_SOCIAL_AUTH_GITHUB_KEY}
      - DJANGO_SOCIAL_AUTH_GITHUB_SECRET=${DJANGO_SOCIAL_AUTH_GITHUB_SECRET}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  celery:
    build: .
    restart: always
    command: bash -c "celery -A chatroom_project worker -l info"
    depends_on:
      - db
      - redis
      - app
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  flower:
    build: .
    restart: always
    command: bash -c "flower -A chatroom_project --address=0.0.0.0  --port=5050"
    depends_on:
      - db
      - redis
      - app
      - celery
    ports:
      - "5050:5050"
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
