version: '3.1'

services:
  db:
    image: postgres:12.6-alpine
    restart: always
    ports:
      - "5432"
    env_file:
      - db.env

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379"

  app:
    build: .
    restart: always
    command: bash -c "/app/entrypoint.sh"
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    env_file:
      - app.env

  celery:
    build: .
    restart: always
    command: bash -c "celery -A chatroom_project worker -l info"
    depends_on:
      - db
      - redis
      - app
    env_file:
      - celery.env

  flower:
    build: .
    restart: always
    command: bash -c "flower -A chatroom_project --address=0.0.0.0  --port=5050"
    depends_on:
      - db
      - redis
      - app
      - celery
    ports:
      - "5050:5050"
    env_file:
      - celery.env
